## Applying user-defined Functions to Numpy and Pandas

In [1]:
import numpy as np 
import pandas as pd 

In [2]:
my_array = np.array([[10,2,13],
                     [21,22,23],
                     [31,32,33],
                     [10,57,20],
                     [20,20,20],
                     [101,91,10]])
my_array

array([[ 10,   2,  13],
       [ 21,  22,  23],
       [ 31,  32,  33],
       [ 10,  57,  20],
       [ 20,  20,  20],
       [101,  91,  10]])

In [6]:
def my_function(x):
    position = np.argmax(x)
    return position
print (np.apply_along_axis(my_function, axis=0, arr=my_array)) # Using axis=0 we can apply that function to all columns:
print (np.apply_along_axis(my_function, axis=1, arr=my_array)) # Using axis=1 we can apply that function to all rows:

[5 5 2]
[2 2 2 1 0 0]


In [26]:
# convert array to dataframe with pre-defined column names
df = pd.DataFrame(data = my_array,columns = ['A', 'B', 'C'])
df

A   B   C
0   15   5  16
1   25  24  25
2   35  34  35
3   14  59  22
4   24  22  22
5  105  93  12

In [19]:
def my_function(x):
    '''
    The Pandas method for determining the position of the highest value is idxmax.
    '''
    z = x.idxmax()
    return z
print(df.apply(my_function, axis=0)) # returns the  position of the highest value in each column

A    5
B    5
C    2
dtype: int64


#### Applying Function to a specific pandas column

In [25]:
def addOne(v):
    v['A'] += 1
    return v

df2 = df.apply(addOne, axis=1)
df2

A   B   C
0   15   5  16
1   25  24  25
2   35  34  35
3   14  59  22
4   24  22  22
5  105  93  12

In [ ]:
df3 = pd.DataFrame()

#### References
1. https://pythonhealthcare.org/2018/04/04/25-applying-user-defined-functions-to-numpy-and-pandas/